
services:
  app:
    container_name: app
    build: ./app
    depends_on:
      - db
    env_file:
      - ./app/src/.env
    volumes:
      - ./app/src:/app
      - static:/app/static
      - media:/app/media
    ports:
      - 8000:8000
    networks:
      - main

  db:
    container_name: db
    image: postgres:14.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pg_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data: {}
  static: {}
  media: {}
